spring.application.name=aegis
server.port=${PORT:8080}

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM565020
spring.datasource.password=190207
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=create

api.security.token.secret=${JWT_SECRET:JLP@aegis2026}